const axios = require('axios');

const testPublish = async () => {
    try {
        const baseURL = 'http://localhost:5000/api';
        
        // 0. Register (in case seed failed or to be sure)
        const email = `testuser_${Date.now()}@example.com`;
        const password = 'password123';
        console.log(`Registering user ${email}...`);
        
        try {
             await axios.post(`${baseURL}/auth/register`, {
                username: `testuser_${Date.now()}`,
                email,
                password
            });
            console.log("Registration successful.");
        } catch (e) {
            console.log("Registration skipped or failed (might exist):", e.message);
        }

        // 1. Login to get token
        console.log("Logging in...");
        const loginRes = await axios.post(`${baseURL}/auth/login`, {
            email,
            password
        });
        
        const token = loginRes.data.token;
        console.log("Login successful. Token received.");

        // 2. Create Quiz
        console.log("Creating Quiz...");
        const quizData = {
            title: "Test Quiz from Script",
            description: "Generated by verification script",
            questions: [
                {
                    questionText: "Is this working?",
                    options: ["Yes", "No", "Maybe", "Unknown"],
                    correctOptionIndex: 0
                }
            ]
        };

        const createRes = await axios.post(`${baseURL}/quizzes`, quizData, {
            headers: {
                Authorization: `Bearer ${token}`
            }
        });

        console.log("Quiz created successfully!");
        console.log("Quiz ID:", createRes.data._id);
        
    } catch (error) {
        console.error("Test Failed:", error.response ? error.response.data : error.message);
    }
};

testPublish();
